### ISSUE TITLE
Homography disk requirement

### ISSUE THREAD

**Issue by sbucaille** [cvg/glue-factory#14]
Hi,
In the README you mention 450Go of disk space required for the `superpoint-open+lightglue_homography.yaml` training config, but after trying to download everything, it failed after not having enough space on my 1To disk, which was empty when I started the script.
Is the number you provided wrong or am I missing something ?

**Comment by sbucaille** [comment]
Used a 4To SSD and the dataset only uses 450Go, maybe at a specific state of the download it required more space, or maybe I messed something up.
Closing this issue

**Comment by sarlinpe** [comment]
The downloading should not use more than 450 + ~50 GB at most:
https://github.com/cvg/glue-factory/blob/692c72f94c8f58976649faf3883b711d59cf6b1e/gluefactory/datasets/homographies.py#L130-L148
