### ISSUE TITLE
About installation

### ISSUE THREAD

**Issue by PeeKaBo0L** [cvg/glue-factory#16]
I'm a novice who has only recently started learning about this and am currently learning LightGlue. 
When I type
python3 -m pip install -e
it warn that -e option requires 1 argument
I don't know what to enter, can you tell me how to do?
Thank you very much!

**Comment by sarlinpe** [comment]
You're missing a `.` after `-e`.

**Comment by PeeKaBo0L** [comment]
> You're missing a after `.``-e`

Thank you for your answer! 
I'm sorry to bother you with a simple question.
But when i type `.` after`-e`
There is a warn:
`ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /root/glue-factory
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)`
Did I miss something again？
I would be grateful if you could answer my question again！

**Comment by sarlinpe** [comment]
You most likely need to update pip and setuptools:
```bash
python -m pip install --upgrade pip setuptools
```

**Comment by PeeKaBo0L** [comment]
> You most likely need to update pip and setuptools:
> 
> ```shell
> python -m pip install --upgrade pip setuptools
> ```

Thank you very much for your answer! This solved my problem perfectly, I can successfully run`python -m gluefactory.eval.hpatches --conf superpoint+lightglue-official --overwrite` thank you very much！！！！！
