### ISSUE TITLE
Performance differences between 2 versions of SuperPoint with pretrained weights

### ISSUE THREAD

**Issue by nobobobo** [cvg/glue-factory#23]
Hi, thank you for your great work! 

While I'm testing two-view pipeline with SuperPoint and LightGlue as the extractor and the matcher with the custom image data pair, I noticed there's a slight difference between the detected keypoints from two versions of SuperPoint weights loaded from `gluefactory.models.extractors.superpoint_open` and `gluefactory_nonfree.superpoint` (Open-sourced SuperPoint and Non-free SuperPoint). (Maybe I should raise this question in this [repo](https://github.com/rpautrat/SuperPoint/)

### Output of SuperPoint (MIT Lincense)
![Screenshot 2023-10-17 at 4 21 52 PM](https://github.com/cvg/glue-factory/assets/31523422/fcd7673b-c42c-447b-b4c0-81258ba34e3e)

### Output of Non-Free SuperPoint
![Screenshot 2023-10-17 at 4 21 59 PM](https://github.com/cvg/glue-factory/assets/31523422/ced37dfe-81fc-4643-a1be-74c5df7f219d)

It seems Non-Free SuperPoint gives relatively reasonable keypoints. And this behavior persists for the image pairs generated by homographies dataset

### Output of SuperPoint (MIT Lincense)
![Screenshot 2023-10-18 at 10 26 22 AM](https://github.com/cvg/glue-factory/assets/31523422/4772a0d7-6c7b-4d14-a3fc-5799c587aec7)

### Output of Non-Free SuperPoint
![Screenshot 2023-10-18 at 10 26 28 AM](https://github.com/cvg/glue-factory/assets/31523422/de2fa46c-8ffb-4a53-931a-4c08772a1d1a)

Also noticed the scores of keypoints detected by open-sourced SuperPoint are extremely low so that most keypoints are likely excluded by thresholding

![Screenshot 2023-10-18 at 10 30 07 AM](https://github.com/cvg/glue-factory/assets/31523422/b36a79e4-cec4-4ddc-8c7d-afeafec486bc)
![Screenshot 2023-10-18 at 10 30 45 AM](https://github.com/cvg/glue-factory/assets/31523422/5aa463b1-3633-4595-940a-84947c8d015f)

I am curious about whether this is an expected behavior of the two versions of SuperPoint weights or due to my misconfiguration.

**Comment by nobobobo** [comment]
uploading two images I used for testing

![01](https://github.com/cvg/glue-factory/assets/31523422/8d372e53-e440-4097-8721-b81ec598ea7d)
![02](https://github.com/cvg/glue-factory/assets/31523422/38a08957-5cec-4f21-a1b2-671f19a167d6)

**Comment by sarlinpe** [comment]
Can you share the code that yields the first results? Here's what I get with your images and SuperPoint-Open:
![sp-open_points](https://github.com/cvg/glue-factory/assets/15985472/29e3d87a-bbc3-4563-8db2-f5d67fb6304f)
![sp-open_matches](https://github.com/cvg/glue-factory/assets/15985472/ed8dc5cd-168a-4542-8eef-1cf63f6ba1e9)
```python
import torch
from gluefactory.utils.image import ImagePreprocessor
from gluefactory.visualization.viz2d import plot_images, plot_keypoints, plot_matches
from gluefactory.models.extractors.superpoint_open import SuperPoint
from gluefactory.models.matchers.nearest_neighbor_matcher import NearestNeighborMatcher

improc = ImagePreprocessor({'resize': 1024})
im0 = improc.load_image('test_data/receipt1.jpg')['image']
im1 = improc.load_image('test_data/receipt2.jpg')['image']

sp = SuperPoint({'nms_radius': 4}).cuda().eval()
with torch.no_grad():
    pred0 = sp({'image': im0.cuda()[None]})
    pred1 = sp({'image': im1.cuda()[None]})

pts0, pts1 = [p['keypoints'].squeeze(0).cpu() for p in (pred0, pred1)]
plot_images([im.permute(1,2,0) for im in (im0, im1)],
            titles=[f'{len(p)} keypoints' for p in (pts0, pts1)])
plot_keypoints([pts0, pts1])


matcher = NearestNeighborMatcher({"distance_thresh": 0.5})
matches = matcher({'descriptors0': pred0['descriptors'], 'descriptors1': pred1['descriptors']})['matches0'].squeeze(0)

plot_images([im.permute(1,2,0) for im in (im0, im1)])
plot_matches(pts0[matches.cpu()!=-1], pts1[matches[matches!=-1].cpu()], a=0.5, lw=1)
```

**Comment by nobobobo** [comment]
Thanks for trying!

I just ran your code snippet on my end, it seems SuperPoint-Open generates different results with two versions of torch: 2.0.1 and 2.1.0. The difference might be because of some changes implemented in the new PyTorch, which was just relased couple days ago. So for now, I will use torch 2.0.1 for workaround. 

![Screenshot 2023-10-18 at 12 44 41 PM](https://github.com/cvg/glue-factory/assets/31523422/f6979065-b4d8-4008-96a9-48ee842a3eba)
![Screenshot 2023-10-18 at 12 41 22 PM](https://github.com/cvg/glue-factory/assets/31523422/06ff0298-3493-4cee-b648-656a84ca6efb)

```
import torch 
print(torch.__version__)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

from gluefactory.utils.image import ImagePreprocessor
from gluefactory.models.extractors.superpoint_open import SuperPoint
from gluefactory.visualization.viz2d import plot_images, plot_keypoints, plot_matches

improc = ImagePreprocessor({'resize': 1024})
im0 = improc.load_image('../../test_images/01.jpeg')['image']
im1 = improc.load_image('../../test_images/02.jpeg')['image']

sp = SuperPoint({'nms_radius': 4}).cuda().eval()
with torch.no_grad():
    pred0 = sp({'image': im0.cuda()[None]})
    pred1 = sp({'image': im1.cuda()[None]})

pts0, pts1 = [p['keypoints'].squeeze(0).cpu() for p in (pred0, pred1)]
plot_images([im.permute(1,2,0) for im in (im0, im1)],
            titles=[f'{len(p)} keypoints' for p in (pts0, pts1)])
plot_keypoints([pts0, pts1])
```

**Comment by sarlinpe** [comment]
I obtain the exact same results with torch `2.1.0+cu121`, `2.0.1+cu117`, and `2.0.0+cu117`.

**Comment by nobobobo** [comment]
Okay, thank you for checking. I will test again with a clean environment here as well. Close this issue for the time being.
