### ISSUE TITLE
Issues with lrscheduler

### ISSUE THREAD

**Issue by AnasAlsharo** [cvg/glue-factory#31]
Hi. During training of the model this error started to appear after the latest update.

line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigAttributeError: Key 'lr_scheduler' is not in struct
    full_key: train.lr_scheduler
    object_type=dict

I believe that configs files needs to be updated as well.

Anas.

**Comment by sarlinpe** [comment]
A typo slipped through a recent PR, will be fixed by https://github.com/cvg/glue-factory/pull/32.
