### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by AlbertoJaenal** [cvg/glue-factory#44]
Hi, 
First of all, thanks and congrats to the researchers and developers for this amazing set of contributions. They are really handy and will impact the community quite positively!!
I was looking through the code to have a better understanding and I hit a place that may have a typo.
[Here](https://github.com/cvg/glue-factory/blob/main/gluefactory/models/utils/losses.py#L72) both neg0 and neg1 are assigned to the weight matrix using the same dimension (m), which may hold true when the number of elements is the same in both images, but out of that case it may not work. 
Shouldn't it be `weights[:, -1, :n] = neg1` ?
Best,
Alberto

**Comment by sarlinpe** [comment]
Good catch. This does not affect the training since `n == m` but we'll fix it.
