### ISSUE TITLE
KeyError: 'loss/total'

### ISSUE THREAD

**Issue by QuangVinh1280** [cvg/glue-factory#62]
![image](https://github.com/cvg/glue-factory/assets/152237142/0f798fce-22b1-4629-994b-9af399ca21bc)
I have a small doubt regarding line 547 of the train.py file. According to the code, conf.train.best_key will be in numerical format, but why is it set as a string in the config section as best_key = 'loss/total'?

**Comment by yuegao998** [comment]
The code here is intended to compare the value of the key named ‘loss/total’ in the results dictionary. However, I am currently encountering a KeyError: 'loss/total' at this point in the code execution. Upon inspection, I have found that the results dictionary is empty. Could you please advise on how to resolve this issue?

**Comment by QuangVinh1280** [comment]
This error arises from inaccurately dividing the train, test, and validation from my dataset to supply to the model, resulting in the val_loader being empty. Thus, the solution involves checking whether your val_loader is indeed empty and then properly re-dividing the train_dataset, test_dataset, and val_dataset for the model (ensuring that none of the datasets are left empty).

**Comment by yuegao998** [comment]
Thank you for identifying the issue with the empty val_loader. Through my efforts, I have not discovered how to correctly divide the dataset into training, testing, and validation sets.Could you please provide a guide on how to properly divide my dataset into training, testing, and validation sets?

**Comment by yuegao998** [comment]
I have resolved my issue. Thank you for your response.

**Comment by ssjsuueusjsh** [comment]
> Thank you for identifying the issue with the empty val_loader. Through my efforts, I have not discovered how to correctly divide the dataset into training, testing, and validation sets.Could you please provide a guide on how to properly divide my dataset into training, testing, and validation sets?

请问一下 如何解决empty val_loader的问题，非常感谢

**Comment by QuangVinh1280** [comment]
![image](https://github.com/cvg/glue-factory/assets/152237142/896562f1-2cf9-40f4-a63c-8e30311ef91f)
You can set it up in the data section of the.yaml file you use for the training process.

**Comment by ssjsuueusjsh** [comment]
> ![image](https://private-user-images.githubusercontent.com/152237142/344883376-896562f1-2cf9-40f4-a63c-8e30311ef91f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDQxMzAsIm5iZiI6MTcxOTkwMzgzMCwicGF0aCI6Ii8xNTIyMzcxNDIvMzQ0ODgzMzc2LTg5NjU2MmYxLTJjZjktNDBmNC1hNjNjLThlMzAzMTFlZjkxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwNzAzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2RjYzQxOWY0ODg4NTU1YWMxZmMwZTBmNThhODljOGEwYWQ0MjYxOTdiOGNiNTE1YzBjMTMwOGVmZjVkNDMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Uh37yt_v0zoSro6hB2Pm6ixv7W2a27pO5ot984MVBzE) You can set it up in the data section of the.yaml file you use for the training process.

非常感谢
