### ISSUE TITLE
pycolmap error

### ISSUE THREAD

**Issue by zj12345648** [cvg/glue-factory#73]
What version of pycolmap should I use？
![屏幕截图 2024-03-30 155349](https://github.com/cvg/glue-factory/assets/42426598/aa66ee2e-2eee-48aa-92bb-f9c6a4846fc9)

**Comment by Phil26AT** [comment]
Hi, [pycolmap-v0.4.0](https://github.com/colmap/pycolmap/releases/tag/v0.4.0) is the version we used. Once pycolmap is stable, we will update glue-factory.
