### ISSUE TITLE
memory not release

### ISSUE THREAD

**Issue by junwei0812** [cvg/glue-factory#75]
Hi, when training the model with superpoint+lsd+gluestick-homography.yaml , memory usage is always increasing，and finally leading to the program to terminate. Anything solutions?

**Comment by Mitix-EPI** [comment]
did you find any solution ?

**Comment by junwei0812** [comment]
> did you find any solution ?

Yeah， It's the bug in pytlsd, try to install it from the github repo, do not use the pip to install it.

**Comment by Mitix-EPI** [comment]
thanks mate !
