### ISSUE TITLE
simpler GT line matching

### ISSUE THREAD

**Issue by Golbstein** [cvg/glue-factory#83]
Hey

I think I've come up with an easier and more straightforward solution to match GT lines, [gt_line_matches_from_pose_depth](https://github.com/cvg/glue-factory/blob/main/gluefactory/geometry/gt_generation.py#L208)

Since we have depth of image0 and image1 and also the relative position between the images, why won't you simply translate the 2d lines to 3d lines (take the image-points that describe the line and project it so you get world xyz point)

Then you've list of lines0_3d (Nx3) and lines1_3d (Nx3)

And to match the line you do the following:

calculate the distance of the edges of line1 to line0 and take the max
this is the metric to use for distance(line_i, line_j)
![Screenshot 2024-04-24 at 19 15 13](https://github.com/cvg/glue-factory/assets/31940058/5ac6bb50-b904-42c2-a47d-4748157adca0)

This will eliminate the sampling step (you're sampling points along each line) and will make the algorithm simpler with less hyperparameters imo.

The pitfall I'm seeing though is when line1 is too short and perpendicular to line0, then the distance will be still small. But to overcome this we can also calculate the angle between each 3d line

**Comment by rpautrat** [comment]
Hi, what you describe is indeed the simplest way to unproject lines to 3D, and this was also our first try when designing GlueStick. However, the main drawback is when you work with incomplete or inaccurate depth: in your case, the unprojection of the lines fully relies on the depth at the two endpoints, so it is very easy to get one of these points fall on a pixel with missing or bad depth. On the contrary, our sampling approach distributes the uncertainty across all the sampled points and can ignore outliers, and is thus more robust to missing or bad depth.

Of course, if you have perfect depth, the approach you propose is simpler.
